version: "3.8"

services:
  front-local:
    container_name: front-local
    build:
      context: ./front
      dockerfile: Dockerfile.local
    platform: linux/amd64
    volumes:
      - ./front:/app:cached
    command: "yarn dev"
    ports:
      - 80:3000
    environment:
      - NODE_ENV=local
    stdin_open: true
    tty: true
    depends_on:
      - laravel-local

volumes:
  db-local-volume:
